name: Deploy to 'hosting' branch
on:
  push:	
    branches:	
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest    
    steps:
    # Checkout
    - uses: actions/checkout@v3

    # Use Node to install dependencies and build
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    # Deploy to `hosting` branch
    - name: Deploy to hosting branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: hosting
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
