name: Deploy to hosting
on:
  push:	
    branches:	
      - develop
      - 4-assess-deploy-via-webhook

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest    
    steps:
    # Checkout
    - uses: actions/checkout@v3

    # Use Node it install dependencies and build
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: |
        yarn install
        yarn build

    # Deploy to `hosting` branch
    #- name: Deploy
    #  uses: s0/git-publish-subdir-action@develop
    #  env:
    #    REPO: self
    #    BRANCH: hosting
    #    FOLDER: build
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
